import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

// Variable font with the width axis, so headings can be stretched wider.
const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  axes: ["wdth"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fredoka.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
